[tasks.attach_db]
run="psql -h ${DB_HOST} -p ${DB_PORT} -U ${DB_USER} ${DB_DATABASE}"

[env]
_.file = '.env'

[tools]
bun = "latest"
java = "21.0.2"
rust = "latest"
"npm:chrome-devtools-mcp" = "latest"
android-sdk = "latest"
"github:vercel-labs/agent-browser" = "latest"
