/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ManagerRouteImport } from './routes/manager'
import { Route as ConfigRouteImport } from './routes/config'
import { Route as AboutRouteImport } from './routes/about'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SourcesIndexRouteImport } from './routes/sources/index'
import { Route as SourcesMediaSourceIdIndexRouteImport } from './routes/sources/$mediaSourceId/index'
import { Route as DocsSwaggerIndexRouteImport } from './routes/docs/swagger/index'
import { Route as SourcesMediaSourceIdMediaIdIndexRouteImport } from './routes/sources/$mediaSourceId/$mediaId/index'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerRoute = ManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigRoute = ConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesIndexRoute = SourcesIndexRouteImport.update({
  id: '/sources/',
  path: '/sources/',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesMediaSourceIdIndexRoute =
  SourcesMediaSourceIdIndexRouteImport.update({
    id: '/sources/$mediaSourceId/',
    path: '/sources/$mediaSourceId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DocsSwaggerIndexRoute = DocsSwaggerIndexRouteImport.update({
  id: '/docs/swagger/',
  path: '/docs/swagger/',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesMediaSourceIdMediaIdIndexRoute =
  SourcesMediaSourceIdMediaIdIndexRouteImport.update({
    id: '/sources/$mediaSourceId/$mediaId/',
    path: '/sources/$mediaSourceId/$mediaId/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/config': typeof ConfigRoute
  '/manager': typeof ManagerRoute
  '/search': typeof SearchRoute
  '/sources/': typeof SourcesIndexRoute
  '/docs/swagger/': typeof DocsSwaggerIndexRoute
  '/sources/$mediaSourceId/': typeof SourcesMediaSourceIdIndexRoute
  '/sources/$mediaSourceId/$mediaId/': typeof SourcesMediaSourceIdMediaIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/config': typeof ConfigRoute
  '/manager': typeof ManagerRoute
  '/search': typeof SearchRoute
  '/sources': typeof SourcesIndexRoute
  '/docs/swagger': typeof DocsSwaggerIndexRoute
  '/sources/$mediaSourceId': typeof SourcesMediaSourceIdIndexRoute
  '/sources/$mediaSourceId/$mediaId': typeof SourcesMediaSourceIdMediaIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/config': typeof ConfigRoute
  '/manager': typeof ManagerRoute
  '/search': typeof SearchRoute
  '/sources/': typeof SourcesIndexRoute
  '/docs/swagger/': typeof DocsSwaggerIndexRoute
  '/sources/$mediaSourceId/': typeof SourcesMediaSourceIdIndexRoute
  '/sources/$mediaSourceId/$mediaId/': typeof SourcesMediaSourceIdMediaIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/about'
    | '/config'
    | '/manager'
    | '/search'
    | '/sources/'
    | '/docs/swagger/'
    | '/sources/$mediaSourceId/'
    | '/sources/$mediaSourceId/$mediaId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/about'
    | '/config'
    | '/manager'
    | '/search'
    | '/sources'
    | '/docs/swagger'
    | '/sources/$mediaSourceId'
    | '/sources/$mediaSourceId/$mediaId'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/about'
    | '/config'
    | '/manager'
    | '/search'
    | '/sources/'
    | '/docs/swagger/'
    | '/sources/$mediaSourceId/'
    | '/sources/$mediaSourceId/$mediaId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AboutRoute: typeof AboutRoute
  ConfigRoute: typeof ConfigRoute
  ManagerRoute: typeof ManagerRoute
  SearchRoute: typeof SearchRoute
  SourcesIndexRoute: typeof SourcesIndexRoute
  DocsSwaggerIndexRoute: typeof DocsSwaggerIndexRoute
  SourcesMediaSourceIdIndexRoute: typeof SourcesMediaSourceIdIndexRoute
  SourcesMediaSourceIdMediaIdIndexRoute: typeof SourcesMediaSourceIdMediaIdIndexRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager': {
      id: '/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof ManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config': {
      id: '/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof ConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources/': {
      id: '/sources/'
      path: '/sources'
      fullPath: '/sources/'
      preLoaderRoute: typeof SourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources/$mediaSourceId/': {
      id: '/sources/$mediaSourceId/'
      path: '/sources/$mediaSourceId'
      fullPath: '/sources/$mediaSourceId/'
      preLoaderRoute: typeof SourcesMediaSourceIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/swagger/': {
      id: '/docs/swagger/'
      path: '/docs/swagger'
      fullPath: '/docs/swagger/'
      preLoaderRoute: typeof DocsSwaggerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources/$mediaSourceId/$mediaId/': {
      id: '/sources/$mediaSourceId/$mediaId/'
      path: '/sources/$mediaSourceId/$mediaId'
      fullPath: '/sources/$mediaSourceId/$mediaId/'
      preLoaderRoute: typeof SourcesMediaSourceIdMediaIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AboutRoute: AboutRoute,
  ConfigRoute: ConfigRoute,
  ManagerRoute: ManagerRoute,
  SearchRoute: SearchRoute,
  SourcesIndexRoute: SourcesIndexRoute,
  DocsSwaggerIndexRoute: DocsSwaggerIndexRoute,
  SourcesMediaSourceIdIndexRoute: SourcesMediaSourceIdIndexRoute,
  SourcesMediaSourceIdMediaIdIndexRoute: SourcesMediaSourceIdMediaIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/solid-start'
declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
