// This file is auto-generated by TanStack Router

import { Route as rootRoute } from './routes/__root'
import { Route as IndexRoute } from './routes/index'

export const routeTree = rootRoute.addChildren([IndexRoute])

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexRoute
      parentRoute: typeof rootRoute
    }
    '/$': { preLoaderRoute: any; parentRoute: any; }
    '/about': { preLoaderRoute: any; parentRoute: any; }
    '/config': { preLoaderRoute: any; parentRoute: any; }
    'docs/swagger': { preLoaderRoute: any; parentRoute: any; }
    '/manager': { preLoaderRoute: any; parentRoute: any; }
    '/search': { preLoaderRoute: any; parentRoute: any; }
    'sources/$mediaSourceId/$mediaId': { preLoaderRoute: any; parentRoute: any; }
    'sources/$mediaSourceId': { preLoaderRoute: any; parentRoute: any; }
    'sources': { preLoaderRoute: any; parentRoute: any; }
  }
}
