/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as SplatRouteImport } from "./routes/$";
import { Route as AboutRouteImport } from "./routes/about";
import { Route as ApiEventsRouteImport } from "./routes/api/events";
import { Route as ApiRpcSplatRouteImport } from "./routes/api/rpc.$";
import { Route as ApiSourcesMediaSourceIdMediaIdRouteImport } from "./routes/api/sources.$mediaSourceId.$mediaId";
import { Route as ApiSourcesMediaSourceIdMediaIdThumbnailRouteImport } from "./routes/api/sources.$mediaSourceId.$mediaId.thumbnail";
import { Route as ApiSourcesMediaSourceIdDumpRouteImport } from "./routes/api/sources.$mediaSourceId.dump";
import { Route as ApiSourcesMediaSourceIdImportRouteImport } from "./routes/api/sources.$mediaSourceId.import";
import { Route as ConfigRouteImport } from "./routes/config";
import { Route as DocsSwaggerIndexRouteImport } from "./routes/docs/swagger/index";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as ManagerRouteImport } from "./routes/manager";
import { Route as SearchRouteImport } from "./routes/search";
import { Route as SourcesMediaSourceIdMediaIdIndexRouteImport } from "./routes/sources/$mediaSourceId/$mediaId/index";
import { Route as SourcesMediaSourceIdIndexRouteImport } from "./routes/sources/$mediaSourceId/index";
import { Route as SourcesIndexRouteImport } from "./routes/sources/index";

const SearchRoute = SearchRouteImport.update({
	id: "/search",
	path: "/search",
	getParentRoute: () => rootRouteImport,
} as any);
const ManagerRoute = ManagerRouteImport.update({
	id: "/manager",
	path: "/manager",
	getParentRoute: () => rootRouteImport,
} as any);
const ConfigRoute = ConfigRouteImport.update({
	id: "/config",
	path: "/config",
	getParentRoute: () => rootRouteImport,
} as any);
const AboutRoute = AboutRouteImport.update({
	id: "/about",
	path: "/about",
	getParentRoute: () => rootRouteImport,
} as any);
const SplatRoute = SplatRouteImport.update({
	id: "/$",
	path: "/$",
	getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
	id: "/",
	path: "/",
	getParentRoute: () => rootRouteImport,
} as any);
const SourcesIndexRoute = SourcesIndexRouteImport.update({
	id: "/sources/",
	path: "/sources/",
	getParentRoute: () => rootRouteImport,
} as any);
const ApiEventsRoute = ApiEventsRouteImport.update({
	id: "/api/events",
	path: "/api/events",
	getParentRoute: () => rootRouteImport,
} as any);
const SourcesMediaSourceIdIndexRoute =
	SourcesMediaSourceIdIndexRouteImport.update({
		id: "/sources/$mediaSourceId/",
		path: "/sources/$mediaSourceId/",
		getParentRoute: () => rootRouteImport,
	} as any);
const DocsSwaggerIndexRoute = DocsSwaggerIndexRouteImport.update({
	id: "/docs/swagger/",
	path: "/docs/swagger/",
	getParentRoute: () => rootRouteImport,
} as any);
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
	id: "/api/rpc/$",
	path: "/api/rpc/$",
	getParentRoute: () => rootRouteImport,
} as any);
const SourcesMediaSourceIdMediaIdIndexRoute =
	SourcesMediaSourceIdMediaIdIndexRouteImport.update({
		id: "/sources/$mediaSourceId/$mediaId/",
		path: "/sources/$mediaSourceId/$mediaId/",
		getParentRoute: () => rootRouteImport,
	} as any);
const ApiSourcesMediaSourceIdImportRoute =
	ApiSourcesMediaSourceIdImportRouteImport.update({
		id: "/api/sources/$mediaSourceId/import",
		path: "/api/sources/$mediaSourceId/import",
		getParentRoute: () => rootRouteImport,
	} as any);
const ApiSourcesMediaSourceIdDumpRoute =
	ApiSourcesMediaSourceIdDumpRouteImport.update({
		id: "/api/sources/$mediaSourceId/dump",
		path: "/api/sources/$mediaSourceId/dump",
		getParentRoute: () => rootRouteImport,
	} as any);
const ApiSourcesMediaSourceIdMediaIdRoute =
	ApiSourcesMediaSourceIdMediaIdRouteImport.update({
		id: "/api/sources/$mediaSourceId/$mediaId",
		path: "/api/sources/$mediaSourceId/$mediaId",
		getParentRoute: () => rootRouteImport,
	} as any);
const ApiSourcesMediaSourceIdMediaIdThumbnailRoute =
	ApiSourcesMediaSourceIdMediaIdThumbnailRouteImport.update({
		id: "/thumbnail",
		path: "/thumbnail",
		getParentRoute: () => ApiSourcesMediaSourceIdMediaIdRoute,
	} as any);

export interface FileRoutesByFullPath {
	"/": typeof IndexRoute;
	"/$": typeof SplatRoute;
	"/about": typeof AboutRoute;
	"/config": typeof ConfigRoute;
	"/manager": typeof ManagerRoute;
	"/search": typeof SearchRoute;
	"/api/events": typeof ApiEventsRoute;
	"/sources/": typeof SourcesIndexRoute;
	"/api/rpc/$": typeof ApiRpcSplatRoute;
	"/docs/swagger/": typeof DocsSwaggerIndexRoute;
	"/sources/$mediaSourceId/": typeof SourcesMediaSourceIdIndexRoute;
	"/api/sources/$mediaSourceId/$mediaId": typeof ApiSourcesMediaSourceIdMediaIdRouteWithChildren;
	"/api/sources/$mediaSourceId/dump": typeof ApiSourcesMediaSourceIdDumpRoute;
	"/api/sources/$mediaSourceId/import": typeof ApiSourcesMediaSourceIdImportRoute;
	"/sources/$mediaSourceId/$mediaId/": typeof SourcesMediaSourceIdMediaIdIndexRoute;
	"/api/sources/$mediaSourceId/$mediaId/thumbnail": typeof ApiSourcesMediaSourceIdMediaIdThumbnailRoute;
}
export interface FileRoutesByTo {
	"/": typeof IndexRoute;
	"/$": typeof SplatRoute;
	"/about": typeof AboutRoute;
	"/config": typeof ConfigRoute;
	"/manager": typeof ManagerRoute;
	"/search": typeof SearchRoute;
	"/api/events": typeof ApiEventsRoute;
	"/sources": typeof SourcesIndexRoute;
	"/api/rpc/$": typeof ApiRpcSplatRoute;
	"/docs/swagger": typeof DocsSwaggerIndexRoute;
	"/sources/$mediaSourceId": typeof SourcesMediaSourceIdIndexRoute;
	"/api/sources/$mediaSourceId/$mediaId": typeof ApiSourcesMediaSourceIdMediaIdRouteWithChildren;
	"/api/sources/$mediaSourceId/dump": typeof ApiSourcesMediaSourceIdDumpRoute;
	"/api/sources/$mediaSourceId/import": typeof ApiSourcesMediaSourceIdImportRoute;
	"/sources/$mediaSourceId/$mediaId": typeof SourcesMediaSourceIdMediaIdIndexRoute;
	"/api/sources/$mediaSourceId/$mediaId/thumbnail": typeof ApiSourcesMediaSourceIdMediaIdThumbnailRoute;
}
export interface FileRoutesById {
	__root__: typeof rootRouteImport;
	"/": typeof IndexRoute;
	"/$": typeof SplatRoute;
	"/about": typeof AboutRoute;
	"/config": typeof ConfigRoute;
	"/manager": typeof ManagerRoute;
	"/search": typeof SearchRoute;
	"/api/events": typeof ApiEventsRoute;
	"/sources/": typeof SourcesIndexRoute;
	"/api/rpc/$": typeof ApiRpcSplatRoute;
	"/docs/swagger/": typeof DocsSwaggerIndexRoute;
	"/sources/$mediaSourceId/": typeof SourcesMediaSourceIdIndexRoute;
	"/api/sources/$mediaSourceId/$mediaId": typeof ApiSourcesMediaSourceIdMediaIdRouteWithChildren;
	"/api/sources/$mediaSourceId/dump": typeof ApiSourcesMediaSourceIdDumpRoute;
	"/api/sources/$mediaSourceId/import": typeof ApiSourcesMediaSourceIdImportRoute;
	"/sources/$mediaSourceId/$mediaId/": typeof SourcesMediaSourceIdMediaIdIndexRoute;
	"/api/sources/$mediaSourceId/$mediaId/thumbnail": typeof ApiSourcesMediaSourceIdMediaIdThumbnailRoute;
}
export interface FileRouteTypes {
	fileRoutesByFullPath: FileRoutesByFullPath;
	fullPaths:
		| "/"
		| "/$"
		| "/about"
		| "/config"
		| "/manager"
		| "/search"
		| "/api/events"
		| "/sources/"
		| "/api/rpc/$"
		| "/docs/swagger/"
		| "/sources/$mediaSourceId/"
		| "/api/sources/$mediaSourceId/$mediaId"
		| "/api/sources/$mediaSourceId/dump"
		| "/api/sources/$mediaSourceId/import"
		| "/sources/$mediaSourceId/$mediaId/"
		| "/api/sources/$mediaSourceId/$mediaId/thumbnail";
	fileRoutesByTo: FileRoutesByTo;
	to:
		| "/"
		| "/$"
		| "/about"
		| "/config"
		| "/manager"
		| "/search"
		| "/api/events"
		| "/sources"
		| "/api/rpc/$"
		| "/docs/swagger"
		| "/sources/$mediaSourceId"
		| "/api/sources/$mediaSourceId/$mediaId"
		| "/api/sources/$mediaSourceId/dump"
		| "/api/sources/$mediaSourceId/import"
		| "/sources/$mediaSourceId/$mediaId"
		| "/api/sources/$mediaSourceId/$mediaId/thumbnail";
	id:
		| "__root__"
		| "/"
		| "/$"
		| "/about"
		| "/config"
		| "/manager"
		| "/search"
		| "/api/events"
		| "/sources/"
		| "/api/rpc/$"
		| "/docs/swagger/"
		| "/sources/$mediaSourceId/"
		| "/api/sources/$mediaSourceId/$mediaId"
		| "/api/sources/$mediaSourceId/dump"
		| "/api/sources/$mediaSourceId/import"
		| "/sources/$mediaSourceId/$mediaId/"
		| "/api/sources/$mediaSourceId/$mediaId/thumbnail";
	fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
	IndexRoute: typeof IndexRoute;
	SplatRoute: typeof SplatRoute;
	AboutRoute: typeof AboutRoute;
	ConfigRoute: typeof ConfigRoute;
	ManagerRoute: typeof ManagerRoute;
	SearchRoute: typeof SearchRoute;
	ApiEventsRoute: typeof ApiEventsRoute;
	SourcesIndexRoute: typeof SourcesIndexRoute;
	ApiRpcSplatRoute: typeof ApiRpcSplatRoute;
	DocsSwaggerIndexRoute: typeof DocsSwaggerIndexRoute;
	SourcesMediaSourceIdIndexRoute: typeof SourcesMediaSourceIdIndexRoute;
	ApiSourcesMediaSourceIdMediaIdRoute: typeof ApiSourcesMediaSourceIdMediaIdRouteWithChildren;
	ApiSourcesMediaSourceIdDumpRoute: typeof ApiSourcesMediaSourceIdDumpRoute;
	ApiSourcesMediaSourceIdImportRoute: typeof ApiSourcesMediaSourceIdImportRoute;
	SourcesMediaSourceIdMediaIdIndexRoute: typeof SourcesMediaSourceIdMediaIdIndexRoute;
}

declare module "@tanstack/solid-router" {
	interface FileRoutesByPath {
		"/search": {
			id: "/search";
			path: "/search";
			fullPath: "/search";
			preLoaderRoute: typeof SearchRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/manager": {
			id: "/manager";
			path: "/manager";
			fullPath: "/manager";
			preLoaderRoute: typeof ManagerRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/config": {
			id: "/config";
			path: "/config";
			fullPath: "/config";
			preLoaderRoute: typeof ConfigRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/about": {
			id: "/about";
			path: "/about";
			fullPath: "/about";
			preLoaderRoute: typeof AboutRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/$": {
			id: "/$";
			path: "/$";
			fullPath: "/$";
			preLoaderRoute: typeof SplatRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/": {
			id: "/";
			path: "/";
			fullPath: "/";
			preLoaderRoute: typeof IndexRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/sources/": {
			id: "/sources/";
			path: "/sources";
			fullPath: "/sources/";
			preLoaderRoute: typeof SourcesIndexRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/api/events": {
			id: "/api/events";
			path: "/api/events";
			fullPath: "/api/events";
			preLoaderRoute: typeof ApiEventsRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/sources/$mediaSourceId/": {
			id: "/sources/$mediaSourceId/";
			path: "/sources/$mediaSourceId";
			fullPath: "/sources/$mediaSourceId/";
			preLoaderRoute: typeof SourcesMediaSourceIdIndexRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/docs/swagger/": {
			id: "/docs/swagger/";
			path: "/docs/swagger";
			fullPath: "/docs/swagger/";
			preLoaderRoute: typeof DocsSwaggerIndexRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/api/rpc/$": {
			id: "/api/rpc/$";
			path: "/api/rpc/$";
			fullPath: "/api/rpc/$";
			preLoaderRoute: typeof ApiRpcSplatRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/sources/$mediaSourceId/$mediaId/": {
			id: "/sources/$mediaSourceId/$mediaId/";
			path: "/sources/$mediaSourceId/$mediaId";
			fullPath: "/sources/$mediaSourceId/$mediaId/";
			preLoaderRoute: typeof SourcesMediaSourceIdMediaIdIndexRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/api/sources/$mediaSourceId/import": {
			id: "/api/sources/$mediaSourceId/import";
			path: "/api/sources/$mediaSourceId/import";
			fullPath: "/api/sources/$mediaSourceId/import";
			preLoaderRoute: typeof ApiSourcesMediaSourceIdImportRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/api/sources/$mediaSourceId/dump": {
			id: "/api/sources/$mediaSourceId/dump";
			path: "/api/sources/$mediaSourceId/dump";
			fullPath: "/api/sources/$mediaSourceId/dump";
			preLoaderRoute: typeof ApiSourcesMediaSourceIdDumpRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/api/sources/$mediaSourceId/$mediaId": {
			id: "/api/sources/$mediaSourceId/$mediaId";
			path: "/api/sources/$mediaSourceId/$mediaId";
			fullPath: "/api/sources/$mediaSourceId/$mediaId";
			preLoaderRoute: typeof ApiSourcesMediaSourceIdMediaIdRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/api/sources/$mediaSourceId/$mediaId/thumbnail": {
			id: "/api/sources/$mediaSourceId/$mediaId/thumbnail";
			path: "/thumbnail";
			fullPath: "/api/sources/$mediaSourceId/$mediaId/thumbnail";
			preLoaderRoute: typeof ApiSourcesMediaSourceIdMediaIdThumbnailRouteImport;
			parentRoute: typeof ApiSourcesMediaSourceIdMediaIdRoute;
		};
	}
}

interface ApiSourcesMediaSourceIdMediaIdRouteChildren {
	ApiSourcesMediaSourceIdMediaIdThumbnailRoute: typeof ApiSourcesMediaSourceIdMediaIdThumbnailRoute;
}

const ApiSourcesMediaSourceIdMediaIdRouteChildren: ApiSourcesMediaSourceIdMediaIdRouteChildren =
	{
		ApiSourcesMediaSourceIdMediaIdThumbnailRoute:
			ApiSourcesMediaSourceIdMediaIdThumbnailRoute,
	};

const ApiSourcesMediaSourceIdMediaIdRouteWithChildren =
	ApiSourcesMediaSourceIdMediaIdRoute._addFileChildren(
		ApiSourcesMediaSourceIdMediaIdRouteChildren,
	);

const rootRouteChildren: RootRouteChildren = {
	IndexRoute: IndexRoute,
	SplatRoute: SplatRoute,
	AboutRoute: AboutRoute,
	ConfigRoute: ConfigRoute,
	ManagerRoute: ManagerRoute,
	SearchRoute: SearchRoute,
	ApiEventsRoute: ApiEventsRoute,
	SourcesIndexRoute: SourcesIndexRoute,
	ApiRpcSplatRoute: ApiRpcSplatRoute,
	DocsSwaggerIndexRoute: DocsSwaggerIndexRoute,
	SourcesMediaSourceIdIndexRoute: SourcesMediaSourceIdIndexRoute,
	ApiSourcesMediaSourceIdMediaIdRoute:
		ApiSourcesMediaSourceIdMediaIdRouteWithChildren,
	ApiSourcesMediaSourceIdDumpRoute: ApiSourcesMediaSourceIdDumpRoute,
	ApiSourcesMediaSourceIdImportRoute: ApiSourcesMediaSourceIdImportRoute,
	SourcesMediaSourceIdMediaIdIndexRoute: SourcesMediaSourceIdMediaIdIndexRoute,
};
export const routeTree = rootRouteImport
	._addFileChildren(rootRouteChildren)
	._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";

declare module "@tanstack/solid-start" {
	interface Register {
		ssr: true;
		router: Awaited<ReturnType<typeof getRouter>>;
	}
}
