import { Buffer } from "node:buffer";
import type { APIEvent } from "@solidjs/start/server";
import { eq } from "drizzle-orm";
import { Open } from "unzipper";
import { db } from "~/infrastructure/db";
import {
  authors,
  mediaAuthors,
  mediaGenerationInfo,
  mediaSources,
  medias,
  mediaTags,
  mediaUrls,
  tags,
} from "~/infrastructure/db/schema";
import { getDriver } from "~/infrastructure/storage/factory";

/**
 * @swagger
 * /api/sources/{mediaSourceId}/import:
 *   post:
 *     summary: Import media data from a ZIP file
 *     description: Imports media data including metadata, tags, and images from a ZIP file generated by the dump API.
 *     tags:
 *       - Media Sources
 *     parameters:
 *       - in: path
 *         name: mediaSourceId
 *         required: true
 *         schema:
 *           type: string
 *           format: uuid
 *         description: The ID of the media source to import into.
 *     requestBody:
 *       required: true
 *       content:
 *         multipart/form-data:
 *           schema:
 *             type: object
 *             properties:
 *               file:
 *                 type: string
 *                 format: binary
 *                 description: The ZIP file to import.
 *     responses:
 *       200:
 *         description: Import successful
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 success:
 *                   type: boolean;
 *                 importedCount:
 *                   type: number;
 *       400:
 *         description: Bad request (missing ID or file)
 *       404:
 *         description: Media source not found
 *       500:
 *         description: Internal server error
 */
export async function POST({ params, request }: APIEvent) {
  try {
    const { mediaSourceId } = params;

    if (!mediaSourceId) {
      return new Response(
        JSON.stringify({ error: "Media Source ID is required" }),
        {
          status: 400,
          headers: { "Content-Type": "application/json" },
        }
      );
    }

    // 1. Fetch Media Source Info
    const mediaSource = await db.query.mediaSources.findFirst({
      where: eq(mediaSources.id, mediaSourceId),
    });

    if (!mediaSource) {
      return new Response(JSON.stringify({ error: "Media Source not found" }), {
        status: 404,
        headers: { "Content-Type": "application/json" },
      });
    }

    // 2. Get File from Request
    const formData = await request.formData();
    const file = formData.get("file") as File;

    if (!(file && file instanceof File)) {
      return new Response(JSON.stringify({ error: "ZIP file is required" }), {
        status: 400,
        headers: { "Content-Type": "application/json" },
      });
    }

    const buffer = Buffer.from(await file.arrayBuffer());
    const directory = await Open.buffer(buffer);

    // 3. Find and Parse dump.json
    const dumpFile = directory.files.find((f) => f.path === "dump.json");
    if (!dumpFile) {
      return new Response(
        JSON.stringify({ error: "dump.json not found in ZIP" }),
        {
          status: 400,
          headers: { "Content-Type": "application/json" },
        }
      );
    }

    const dumpContent = await dumpFile.buffer();
    const dumpData = JSON.parse(dumpContent.toString("utf-8"));

    if (!Array.isArray(dumpData)) {
      return new Response(JSON.stringify({ error: "Invalid dump format" }), {
        status: 400,
        headers: { "Content-Type": "application/json" },
      });
    }

    const driver = getDriver(mediaSource);
    let importedCount = 0;

    // 4. Process Each Media Item
    for (const item of dumpData) {
      const imagePathInZip = `images/${item.filePath}`;
      const imageFile = directory.files.find((f) => f.path === imagePathInZip);

      if (imageFile) {
        const content = await imageFile.buffer();
        await driver.put(item.filePath, content);
      } else {
        // Continue even if file is missing? Maybe it's metadata only update.
      }

      // biome-ignore lint/suspicious/noExplicitAny: tx type inference issue
      await db.transaction(async (tx: any) => {
        await processImportItem(tx, mediaSourceId, item);
      });

      importedCount++;
    }

    return new Response(
      JSON.stringify({
        success: true,
        importedCount,
        message: `Successfully imported ${importedCount} items`,
      }),
      {
        status: 200,
        headers: { "Content-Type": "application/json" },
      }
    );
  } catch (error) {
    return new Response(
      JSON.stringify({
        error: "Failed to import data",
        details: error instanceof Error ? error.message : String(error),
      }),
      {
        status: 500,
        headers: { "Content-Type": "application/json" },
      }
    );
  }
}

// Helper function to process individual item import in transaction
// biome-ignore lint/suspicious/noExplicitAny: dumpData is loosely typed from JSON
async function processImportItem(tx: any, mediaSourceId: string, item: any) {
  const mediaId = await importMediaRecord(tx, mediaSourceId, item);
  await importMediaTags(tx, mediaId, item.tags);
  await importMediaAuthors(tx, mediaId, item.authors);
  await importMediaGenerationInfo(tx, mediaId, item.generationInfo);
  await importMediaUrls(tx, mediaId, item.sourceUrls);
}

// biome-ignore lint/suspicious/noExplicitAny: tx is complex drizzle type
async function importMediaRecord(tx: any, mediaSourceId: string, item: any) {
  const [insertedMedia] = await tx
    .insert(medias)
    .values({
      mediaSourceId,
      filePath: item.filePath,
      fileName: item.fileName,
      mediaType: ["image", "video", "audio"].includes(item.mediaType)
        ? item.mediaType
        : "image",
      width: item.width,
      height: item.height,
      fileSize: item.fileSize,
      description: item.description,
      createdAt: new Date(item.createdAt),
      modifiedAt: new Date(item.modifiedAt),
      indexedAt: new Date(item.indexedAt),
      status: "active",
    })
    .onConflictDoUpdate({
      target: [medias.mediaSourceId, medias.filePath],
      set: {
        description: item.description,
        modifiedAt: new Date(item.modifiedAt),
        width: item.width,
        height: item.height,
        fileSize: item.fileSize,
      },
    })
    .returning();
  return insertedMedia.id;
}

// biome-ignore lint/suspicious/noExplicitAny: tx is complex drizzle type
async function importMediaTags(tx: any, mediaId: string, tagsList: any[]) {
  if (!(tagsList && Array.isArray(tagsList))) {
    return;
  }

  await tx.delete(mediaTags).where(eq(mediaTags.mediaId, mediaId));

  for (const tag of tagsList) {
    let tagId: string;
    const existingTag = await tx.query.tags.findFirst({
      where: eq(tags.name, tag.name),
    });

    if (existingTag) {
      tagId = existingTag.id;
    } else {
      const [newTag] = await tx
        .insert(tags)
        .values({
          name: tag.name,
          source: "imported",
        })
        .returning();
      tagId = newTag.id;
    }

    await tx.insert(mediaTags).values({
      mediaId,
      tagId,
      tagType: tag.type || "positive",
      confidence: tag.confidence,
      source: "imported",
    });
  }
}

async function importMediaAuthors(
  // biome-ignore lint/suspicious/noExplicitAny: tx is complex drizzle type
  tx: any,
  mediaId: string,
  // biome-ignore lint/suspicious/noExplicitAny: loose type from JSON
  authorsList: any[]
) {
  if (!(authorsList && Array.isArray(authorsList))) {
    return;
  }

  await tx.delete(mediaAuthors).where(eq(mediaAuthors.mediaId, mediaId));

  for (const author of authorsList) {
    let authorId: string;
    const existingAuthor = await tx.query.authors.findFirst({
      where: eq(authors.name, author.name),
    });

    if (existingAuthor) {
      authorId = existingAuthor.id;
    } else {
      const [newAuthor] = await tx
        .insert(authors)
        .values({
          name: author.name,
          accountId: author.accountId,
        })
        .returning();
      authorId = newAuthor.id;
    }

    await tx.insert(mediaAuthors).values({
      mediaId,
      authorId,
    });
  }
}

// biome-ignore lint/suspicious/noExplicitAny: tx is complex drizzle type
async function importMediaGenerationInfo(tx: any, mediaId: string, info: any) {
  if (!info) {
    return;
  }

  await tx
    .insert(mediaGenerationInfo)
    .values({
      mediaId,
      prompt: info.prompt,
      negativePrompt: info.negativePrompt,
      modelName: info.modelName,
      seed: info.seed,
      steps: info.steps,
      cfgScale: info.cfgScale,
      aiGenerated: info.aiGenerated,
      workflow: info.workflow,
      metadata: info.metadata,
    })
    .onConflictDoUpdate({
      target: mediaGenerationInfo.mediaId,
      set: {
        prompt: info.prompt,
        negativePrompt: info.negativePrompt,
        modelName: info.modelName,
        seed: info.seed,
        steps: info.steps,
        cfgScale: info.cfgScale,
        workflow: info.workflow,
        metadata: info.metadata,
      },
    });
}

// biome-ignore lint/suspicious/noExplicitAny: tx is complex drizzle type
async function importMediaUrls(tx: any, mediaId: string, urlsList: any[]) {
  if (!(urlsList && Array.isArray(urlsList))) {
    return;
  }

  await tx.delete(mediaUrls).where(eq(mediaUrls.mediaId, mediaId));
  for (const url of urlsList) {
    await tx.insert(mediaUrls).values({
      mediaId,
      url,
    });
  }
}
